project:
  type: website
  output-dir: 'docs'

website:
  title: "Writing R Packages for the Public Good: A workshop"
  repo-url: https://github.com/EpiForeSITE/r-pkgs-workshop
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - program.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



